### ISSUE TITLE
Instances size issue

### ISSUE THREAD

**Issue by AwaisG** [aws-samples/aws-sagemaker-heart-disease-prediction#1]
I have an issue with large instances due to a limited version of my account and limitation of the free tier. I changed the instance from large to medium but it says instance type should be large not medium, is there any way in which I can run this code in ml.t2.medium instance? your kind help is required.
My error is as follow: 
An error occurred (ValidationException) when calling the CreateTrainingJob operation: 1 validation error detected: Value 'ml.t2.medium' at 'resourceConfig.instanceType' failed to satisfy constraint: Member must satisfy enum value set: [ml.p2.xlarge, ml.m5.4xlarge, ml.m4.16xlarge, ml.p3.16xlarge, ml.m5.large, ml.p2.16xlarge, ml.c4.2xlarge, ml.c5.2xlarge, ml.c4.4xlarge, ml.c5.4xlarge, ml.g4dn.xlarge, ml.g4dn.12xlarge, ml.c4.8xlarge, ml.g4dn.2xlarge, ml.c5.9xlarge, ml.g4dn.4xlarge, ml.c5.xlarge, ml.g4dn.16xlarge, ml.c4.xlarge, ml.g4dn.8xlarge, ml.c5.18xlarge, ml.p3dn.24xlarge, ml.p3.2xlarge, ml.m5.xlarge, ml.m4.10xlarge, ml.m5.12xlarge, ml.m4.xlarge, ml.m5.24xlarge, ml.m4.2xlarge, ml.p2.8xlarge, ml.m5.2xlarge, ml.p3.8xlarge, ml.m4.4xlarge]

**Comment by mrahimi991** [comment]
@AwaisG - Unfortunately, ml.t2.medium is not supported for training.  You can open a support ticket from your AWS Console to increase the limit on your account.  You can also find support and pricing of training instances at https://aws.amazon.com/sagemaker/pricing/

**Comment by annamykol** [comment]
@AwaisG 
Try to set "ml.c4.xlarge"
it helped me
