### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ShreyaOswal21** [aws-samples/aws-sagemaker-heart-disease-prediction#2]
when I use postman or API Gateway,I get an Internal Server Error

**Comment by mrahimi991** [comment]
@user1234598 - Thank you for pointing out this error.  There was a data type conversion and I have updated the source code and generated a new heart-functions library (heart_function-1.0.0.jar).  Please go ahead and download the new heart-function jar and upload it to your S3 bucket.  You will have to run the cloudformation template again to update your lambda code.  Please let me know if you run into additional issues.

**Comment by mrahimi991** [comment]
Code updated to resolve internal server issue.

**Comment by ShreyaOswal21** [comment]
> @user1234598 - Thank you for pointing out this error. There was a data type conversion and I have updated the source code and generated a new heart-functions library (heart_function-1.0.0.jar). Please go ahead and download the new heart-function jar and upload it to your S3 bucket. You will have to run the cloudformation template again to update your lambda code. Please let me know if you run into additional issues.

Works now! Thank you.
