### ISSUE TITLE
Internal Server error using Postman,but works fine directly from API Gateway.

### ISSUE THREAD

**Issue by ShreyaOswal21** [aws-samples/aws-sagemaker-heart-disease-prediction#3]
When the CloudFormation url is invoked using Postman,an Internal Server Error is displayed.However,when the API is invoked directly from API Gateway,there is no error and the output is correctly displayed.

**Comment by mrahimi991** [comment]
Do you mind uploading a screenshot of your postman ?

**Comment by ShreyaOswal21** [comment]
> Do you mind uploading a screenshot of your postman ?
sure
![image](https://user-images.githubusercontent.com/71219291/93498801-da54ef80-f92f-11ea-985d-d9a5b3c63887.png)

**Comment by mrahimi991** [comment]
Looks like you are passing data as query parameters in the URL.  You have to pass the data as JSON in the body of the request. 

In postman, click on Body, then choose  'raw' and select json as the data type.  Then you can put the json request data and click submit.

**Comment by mrahimi991** [comment]
The API does not take the input as query parameters, it needs to be in the POST body.  Please see comment above.
